name: Update GitHub Profile Objective

on:
  schedule:
    - cron: '0 * * * *' # Run hourly
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Objective Section
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "GÜNCEL GÖREV: Aktivite Logları Güncellendi 🚀"
          MAX_LINES: 1
          CUSTOM_SECTION: "objective"
